#eureka
eureka.server=http://localhost:8761/eureka/
#swagger
springfox.documentation.swagger.v2.path=/api-docs
#jwt
jwt.secret=(ReTaIlEr)&71025207.NeT.In
jwt.token.validity=864000
jwt.token.rem.me.validity=2592000
jwt.token.prefix= Bearer 

#Spring configs
spring.main.allow-bean-definition-overriding=true
spring.main.banner-mode=off
spring.servlet.multipart.enabled=false

#jasypt configs
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.password=erp#secret$71025207

#app port's
gateway.server.port=8080
core.server.port=7001
report.server.port=5001

#log
root.logging.level=INFO
logging.level.org.springframework=INFO 

#zipkin
spring.zipkin.enabled=false

spring.mail.host=smtp.zoho.com
#spring.mail.host=smtp.gmail.com
#spring.mail.port=465 or 587
spring.mail.port=465
spring.mail.default-encoding=UTF-8
spring.mail.username=info@retailer.net.in
spring.mail.password=sam_coder
#spring.mail.username=babisumit@gmail.com
#spring.mail.password=sam_arc123

spring.mail.protocol=smtp

# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# TLS , port 587
#spring.mail.properties.mail.smtp.starttls.enable=true

# SSL, post 465
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory

spring.mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback: false
spring.mail.properties.mail.smtp.startssl.enable: true
spring.mail.properties.mail.smtp.socketFactory.port: 465
spring.mail.properties.mail.smtp.debug: true



app.mail.do-not-reply.from.name=Do Not Reply
app.mail.do-not-reply.from.email=donotreply@retailer.net.in
app.mail.do-not-reply.reply.email=donotreply@retailer.net.in

app.mail.from.name=Team Retailer
app.mail.from.email=info@retailer.net.in
app.mail.reply.email=info@retailer.net.in
#app.mail.from.email=babisumit@gmail.com
#app.mail.reply.email=babisumit@gmail.com

app.mail.admin.team.email=babisumit@gmail.com

app.base.url=http://localhost/erp-ui