#Redis configuration
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=erp@710252@omhrmrknmh

#log
logging.level.com.erp.auth.AuthApp=TRACE
logging.pattern.console=%d{yy-MM-dd E HH:mm:ss.SSS} %-5p [%thread] %logger %X{correlation-id} %m%n

#Sring datasource properties
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/erp?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
spring.datasource.username = root
spring.datasource.password = sam_coder
spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.validator.apply_to_ddl=false
#spring.jpa.properties.hibernate.check_nullability=true
debug=true
hibernate.hbm2ddl.auto=update
#Spring jackson properties
spring.jackson.serialization.write_dates_as_timestamps=false

#Integrator app specific properties
date.time.format=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
date.format=yyyy-MM-dd