export enum IncidentStatus {
    OPEN,
    ASSIGNED,
    NEED_CLARIFICATION,
    PROVIDED_CLARIFICATION,
    //closer status
    WORK_IN_PROGRESS,
    CLOSED,
    
    SLA_ABOUT_TO_BREACH,
    SLA_BREACHED,
    REOPEND,
    ON_HOLD,
    PENDING_FROM_VENDOR,
    PENDING_FROM_REQUESTER,
    ALL,
    DRAFT,
}
