export enum IncidentStatus {
    OPEN,
    ASSIGNED,
    NEED_CLARIFICATION,
    PROVIDED_CLARIFICATION,
    WORK_IN_PROGRESS,
    CLOSED,
    SLA_ABOUT_TO_BREACH,
    SLA_BREACHED,
    ASSIGNED_REOPENED,
    ON_HOLD,
    PENDING_FROM_VENDOR,
    PENDING_FROM_REQUESTER,
    ALL,
    DRAFT
}
