server:
  port: ${gateway.server.port}
  tomcat:
    accesslog:
      enabled: true
      directory: "/tmp"
      prefix: access
      buffered: false
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: "%h %l %u %t %r %s %b"

hystrix:
  command:
    default:
      circuitBreaker:
        enabled: false

debug: false

management:
  security:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.server}

ribbon:
  connectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 1
  eureka:
    enabled: true

zuul:
  retryable: true
  routes:
    auth-v1:
      path: /api/v1/auth/**
      serviceId: auth-api

