package com.centram.domain.enumarator;

public enum TaskType {
    TRAVEL, TRAINING, REQ_ANALYSIS_BACKLOG_GROOM, ARCHITECTURE_DESIGN, CONFIGURATION_BUILD, MIGRATION, QA_TESTING, USER_ACCEPTANCE_TESTING, RELEASE_DEPLOYMENT, WARRANTY_SUPPORT_HYPERCARE, SPRINT_PLNG_PRJ_SRV_DEL_MGMT, TRANSITION, PROJECT_TRAINING_KEDB_ACT, REVIEW_REWORK, CONT_IMPROVEMENT_AUTOMATION, BCP, OTHER
}