#swagger
springfox.documentation.swagger.v2.path=/api-docs
springfox.documentation.enabled=false

#server
server.port=7001

#actuator
management.endpoints.web.exposure.include=*

#spring
spring.application.name=centram-core-api
spring.main.allow-bean-definition-overriding=true
spring.main.banner-mode=off
spring.servlet.multipart.enabled=true
spring.http.multipart.enabled=true
spring.http.multipart.max-file-size=3MB
spring.http.multipart.max-request-size=15MB

#mail
#spring.sendgrid.api-key=
#spring.sendgrid.proxy.host=
#spring.sendgrid.proxy.port=
#spring.mail.jndi-name=
spring.mail.test-connection=false
spring.mail.protocol=smtp
spring.mail.host=smtp.zoho.in
spring.mail.port=465
spring.mail.default-encoding=UTF-8
spring.mail.username=support@centram.live
spring.mail.password=ENC(dmCNpTH4V3YJ8kOUJFnYTK+P6dezy5Np)
#=sqvsvEth2xSn

# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
spring.mail.properties.mail.smtp.startssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.debug=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.store.protocol=pop3
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug.auth=true

#Redis configuration
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
#spring.redis.password=erp@710252@omhrmrknmh
#centram@live#716551
spring.redis.password=ENC(aeaFPjwTYiyuBw/ax7Cv9Yx4sxjn8fpOcru0mNwK0N0=)

#Sring datasource properties
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/centram?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
spring.datasource.username = root
spring.datasource.password = ENC(dJuFtbxZtiTKEuC9U89g/wqkjAp1Zlyl)
spring.datasource.testWhileIdle = true
spring.datasource.validationQuery = SELECT 1
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL55Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.show-sql=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.validator.apply_to_ddl=false
#spring.jpa.properties.hibernate.check_nullability=true
debug=false
hibernate.hbm2ddl.auto=none
#Spring jackson properties
spring.jackson.serialization.write_dates_as_timestamps=false

#jwt
#[(CeNtRM)&71025207.LiVE]
jwt.secret=ENC(FnM/43+D7dXQrrXV4sU4f4ZEnO2hzgxbaeLV4O2+oSw7/c5iWyejVw==)
jwt.token.validity=864000
jwt.token.rem.me.validity=2592000
jwt.token.prefix=Bearer 

#jasypt configs
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.password=UIbhssh^^51771771@!!0m0!!n==!hasg@3#==

#tomcat
server.tomcat.accesslog.buffered=true
server.tomcat.accesslog.directory=/var/log/centram/tomcat
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd
server.tomcat.accesslog.pattern=common
server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.rename-on-rotate=false
server.tomcat.accesslog.request-attributes-enabled=false
server.tomcat.accesslog.rotate=true
server.tomcat.accesslog.suffix=.log

#log
root.logging.level=INFO
logging.level.org.springframework.*=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.boot=INFO
logging.level.org.springframework.web=INFO
logging.level.CoreApp=INFO
logging.path=/var/log/centram
logging.file.name=${logging.path}/${spring.application.name}.log
logging.pattern.rolling-file-name=${spring.application.name}-%d{yyyy-MM-dd}.%i.log
logging.pattern.console=%d{yy-MM-dd E HH:mm:ss.SSS} %-5p [%thread] %logger %X{CorrelationId:-NA} %m%n
logging.pattern.file=%d{yy-MM-dd E HH:mm:ss.SSS} %-5p [%thread] %logger %X{CorrelationId:-NA} %m%n
logging.file.max-size=5MB
logging.file.total-size-cap=30MB
logging.file.max-history=30
#logging.file.clean-history-on-start=true

#camel
camel.thread.pool.name=centram-batch-camel-thread
camel.thread.pool.size=10
camel.thread.pool.max-size=15
camel.thread.pool.max-queue-size=250
camel.thread.pool.alive-time=2500000000000
camel.integrator.context-path=/api/v1/*

# app specific properties
app.date.time.format=yyyy-MM-dd'T'HH:mm:ss
app.date.format=yyyy-MM-dd

app.mail.do-not-reply.from.name=Do Not Reply
app.mail.do-not-reply.from.email=donotreply@centram.live
app.mail.do-not-reply.reply.email=donotreply@centram.live

app.name=Centram
app.mail.from.name=Team Centram
app.mail.from.email=support@centram.live
app.mail.reply.email=support@centram.live
app.mail.admin.team.email=support@centram.live

app.base.url=http://3.111.47.178

app.allowed.origins=http://3.111.47.178,http://3.111.47.178:7001

app.default.incident.prefix=INC
app.default.asset.prefix=AST

app.ws.endpoint=/app-ws-notification
app.ws.broker.prefix=/topic
app.ws.destination.prefix=/app
app.ws.username.key=app_ws_client_shared_user
app.ws.username=CtlK1GGkDyJg54uGZ7CJoF8m5zBI0tHJeXL+gG4n0us=
app.ws.password.key=app_ws_client_shared_pass
app.ws.password=ErnI2rP5Q5AU+vo9cGjf1CPJCwewgKK6z3RA/Kog+JY=