import { Base } from "./Base";
import { IncidentStatus } from "./enumerator/IncidentStatus";
import { Status } from "./enumerator/Status";
import { IncidentCommunication } from "./IncidentCommunication";
import { Priority } from "./Priority";
import { TimeEntry } from "./TimeEntry";
import { User } from "./User";

export class Incident extends Base {
    id: number;
    moduleId: number;
    subModuleId: number;
    title: string;
    incidentNo: string;
    priority: Priority;
    watchList: string[];
    moduleName: string;
    subModuleName: string;
    prevStatus: any;
    status: any;
    reOpened: boolean;
    slaBreached: boolean;
    raisedUser: User;
    assignedUser: User;
    communications: IncidentCommunication[];
    raisedAt: any;
    slaAt: any;
    holdAt: any;
    organisation: any;
    incidentType: any;
    feedbackProvided: boolean;
    assetApproved: boolean;
    allocated: boolean;
    deAllocated: boolean;
    oldAssetId: number;
    ticketType: string;
    oldAsset: string;
    asset: any;
    assetValidity: any;
    allocationDateTime: any;
    deallocationDateTime: any;
    expectedTime: string;
    timeEntries: TimeEntry[];
    approvalRequired: boolean;
    validityExpirationMessageSent: boolean;
    validityExpiredMessageSent: boolean;
    constructor() {
        super();
        this.id = null;
        this.moduleId = null;
        this.subModuleId = null;
        this.title = '';
        this.incidentNo = '';
        this.priority = new Priority();
        this.watchList = [];
        this.status = IncidentStatus.OPEN;
        this.raisedUser = new User();
        this.assignedUser = new User();
        this.communications = [];
        this.raisedAt = null;
        this.slaAt = null;
        this.incidentType = 1;
        this.feedbackProvided = false;
        this.asset = null;
        this.assetApproved = false;
        this.ticketType = null;
        this.oldAsset = null;
        this.assetValidity = null;
        this.allocationDateTime = null;
        this.deallocationDateTime = null;
        this.expectedTime = null;
        this.timeEntries = [];
        this.slaBreached = false;
        this.reOpened = false;
        this.approvalRequired = false;
        this.validityExpirationMessageSent = false;
        this.validityExpiredMessageSent = false;
    }
}
export interface IncidentList {
    content: Incident[];
    totalElements: number;
}