#Camel properties
camel.thread.pool.name=kyte-integrator-camel-thread
camel.thread.pool.size=10
camel.thread.pool.max-size=15
camel.thread.pool.max-queue-size=250
camel.thread.pool.alive-time=2500000000000