/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.erp.auth.api.interfaces;

import com.erp.common.vo.ActionVO;
import com.erp.domain.Action;
import io.swagger.annotations.*;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-05-20T12:19:48.018Z")
@Api(value = "actions", description = "the actions API")
@RequestMapping(value = "/api/v1/action")
public interface IActionApi {

    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Get all actions", nickname = "getActions", notes = "Returns all action", response = ActionVO.class, responseContainer = "List", tags = {"action",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Action.class, responseContainer = "List")
    })
    @RequestMapping(value = "/all",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Page<Action>> getActions(@ApiParam(value = "Pageable parameters", required = false) Pageable pageable);

}
