/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.erp.auth.api.interfaces;

import com.erp.domain.Module;
import io.swagger.annotations.*;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.math.BigInteger;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-05-20T12:19:48.018Z")
@Api(value = "modules", description = "the modules API")
@RequestMapping(value = "/api/v1/module")
public interface IModulesApi {

    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Get all module", nickname = "getModules", notes = "Returns all module", response = Module.class, responseContainer = "List", tags = {"module",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Module.class, responseContainer = "List")})
    @RequestMapping(value = "/",
            produces = {"application/json"},
            method = RequestMethod.GET)
    public ResponseEntity<Page<Module>> getModules(@ApiParam(value = "Pageable parameters", required = false) Pageable pageable);

    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Find module by module id", nickname = "getModuleById", notes = "Find module by module id", response = Module.class, tags = {"module",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Module.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "Invalid id supplied")})
    @RequestMapping(value = "/{moduleId}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    public ResponseEntity<Module> getModuleById(@ApiParam(value = "id of module to return", required = true) @PathVariable("moduleId") BigInteger moduleId);


}
