/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.erp.auth.api.interfaces;

import com.erp.domain.Permission;
import io.swagger.annotations.*;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.math.BigInteger;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-05-20T12:19:48.018Z")

@Api(value = "permission", description = "the permission API")
@RequestMapping(value = "/api/v1/permission")
public interface IPermissionApi {

    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Add a new permission", nickname = "addPermission", notes = "", tags = {"permission",})
    @ApiResponses(value = {
            @ApiResponse(code = 405, message = "Invalid input")})
    @RequestMapping(value = "/",
            produces = {"application/json"},
            consumes = {"application/json",},
            method = RequestMethod.POST)
    ResponseEntity<Permission> addPermission(@ApiParam(value = "Permission object that needs to be added", required = true) @Valid @RequestBody Permission body);


    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Update an existing permission", nickname = "updatePermission", notes = "", tags = {"permission",})
    @ApiResponses(value = {
            @ApiResponse(code = 400, message = "Invalid ID supplied"),
            @ApiResponse(code = 404, message = "Permission not found"),
            @ApiResponse(code = 405, message = "Validation exception")})
    @RequestMapping(value = "/",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.PUT)
    ResponseEntity<Permission> updatePermission(@ApiParam(value = "Permission object that needs to be added to the store", required = true) @Valid @RequestBody Permission body);

    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Get all Permissons", nickname = "getPermissions", notes = "Get all Permissons", response = Permission.class, responseContainer = "List", tags = {"permission",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Permission.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "Invalid status value")})
    @RequestMapping(value = "/all",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Page<Permission>> getPermissions(@ApiParam(value = "Pageable parameters", required = false) Pageable pageable);

    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Get Permisson", nickname = "getPermission", notes = "Get Permisson", response = Permission.class, tags = {"permission",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Permission.class),
            @ApiResponse(code = 400, message = "Invalid status value")})
    @RequestMapping(value = "/",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Permission> getPermission(@ApiParam(value = "id of permission to return", required = true) @PathVariable("permissionId") BigInteger permissionId);

    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Find permissionn by role id", nickname = "getPermissionByRoleId", notes = "Find permissionn by role id", response = Permission.class, responseContainer = "List", tags = {"permission",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Permission.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "Invalid id supplied"),
            @ApiResponse(code = 404, message = "Permission not found")})
    @RequestMapping(value = "/{roleId}/role",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Page<Permission>> getPermissionByRoleId(@ApiParam(value = "id of role to return", required = true) @PathVariable("roleId") BigInteger roleId, @ApiParam(value = "Pageable parameters", required = false) Pageable pageable);

}
