/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.erp.auth.api.interfaces;

import com.erp.domain.Role;
import io.swagger.annotations.*;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.math.BigInteger;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-05-20T12:19:48.018Z")

@Api(value = "roles", description = "the roles API")
@RequestMapping(value = "/api/v1/role")
public interface IRolesApi {

    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Get all Roles", nickname = "getRoles", notes = "Get all Roles", response = Role.class, responseContainer = "List", tags = {"role",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Role.class, responseContainer = "List"),
            @ApiResponse(code = 400, message = "Invalid status value")})
    @RequestMapping(value = "/all",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Page<Role>> getRoles(@ApiParam(value = "Pageable parameters", required = false) Pageable pageable);

    @ApiOperation(authorizations = {@Authorization(value = "JWT")}, value = "Find role by id", nickname = "getRoleById", notes = "Find role by id", response = Role.class, tags = {"role",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Role.class),
            @ApiResponse(code = 400, message = "Invalid name supplied"),
            @ApiResponse(code = 404, message = "Role not found")})
    @RequestMapping(value = "/{roleId}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Role> getRoleById(@ApiParam(value = "id of role to return", required = true) @PathVariable("roleId") BigInteger roleId);
}
