/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.erp.auth.api.interfaces;


import com.erp.common.dto.AuthRequestDTO;
import com.erp.common.dto.LoggedInUserDTO;
import com.erp.domain.User;
import io.swagger.annotations.*;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.math.BigInteger;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-05-20T12:19:48.018Z")

@Api(value = "users", description = "the users API")
@RequestMapping(value = "/api/v1/user")
public interface IUsersApi {
























}
